2025-07-02 11:03:53,073 | ERROR | Ошибка в send_system_stats: Telegram server says - Bad Request: chat not found
Traceback (most recent call last):
  File "/app/src/infrastructure/taskiq/tasks.py", line 65, in send_system_stats
    await bot.send_message(chat_id='reherherhrehre', text=msg, parse_mode='HTML')
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 2850, in send_message
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 478, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found
2025-07-02 11:04:02,280 | ERROR | Ошибка в send_system_stats: Telegram server says - Bad Request: chat not found
Traceback (most recent call last):
  File "/app/src/infrastructure/taskiq/tasks.py", line 65, in send_system_stats
    await bot.send_message(chat_id='reherherhrehre', text=msg, parse_mode='HTML')
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 2850, in send_message
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 478, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found
2025-07-02 11:05:02,280 | ERROR | Ошибка в send_system_stats: Telegram server says - Bad Request: chat not found
Traceback (most recent call last):
  File "/app/src/infrastructure/taskiq/tasks.py", line 65, in send_system_stats
    await bot.send_message(chat_id=ADMIN_CHAT_ID, text=msg, parse_mode='HTML')
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 2850, in send_message
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 478, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 185, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found
